name: CI - Eureka Server

on:
  push:
    branches: [ "main"]
    paths:
      - 'eureka-server/**'
      - '.github/workflows/ci-eureka.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'eureka-server/**'
      - '.github/workflows/ci-eureka.yml'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eureka-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x ../gradlew

      - name: Build and test with Gradle
        run: ../gradlew clean build --no-daemon

      - name: Upload build artifacts (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: eureka-server-jar
          path: eureka-server/build/libs/*.jar